[options]
addons_path = E:\RMA_odoo\odoo17\odoo\addons,E:\RMA_odoo\odoo17_project\custom_addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 12345
db_name = odoo_library
http_port = 8069
admin_passwd = nsfq-iehw-jy2i
data_dir = E:\RMA_odoo\odoo17_project\data
log_level = info
workers = 0